---
dist: trusty
language: perl
perl:
  - "5.10"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get -y install ksh shellcheck libtest-perl-critic-perl"
install: "/bin/true"
script: "prove -v"
